language: ruby
rvm:
  - 2.5.0
addons:
  postgresql: 9.6
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database file_easy_test;' -U postgres
dist: trusty
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec -fd
  